// Generates `doc/tokens.md`: one row per `IxThemeColorToken` with the value
// the classic light and dark palettes resolve it to.
//
// Usage (from packages/ix_flutter):
//   dart run tool/gen_token_table.dart
//
// The rows are driven by the real `IxThemeColorToken` enum (imported below),
// and the values are read out of the two generated palette sources that
// define `IxClassicLightColors.palette` / `IxClassicDarkColors.palette`.
// The palettes are read as source rather than imported because they pull in
// `package:flutter/material.dart` for `Color`, which the standalone Dart VM
// cannot compile ("Crash when compiling: type 'InvalidType' is not a subtype
// of type 'FunctionType' in type cast"); a token missing from either palette
// fails the run instead of silently emitting a hole.
//
// `doc/tokens.md` is generated, never hand-edited: CI regenerates it and
// fails on a diff (see .github/workflows/ci.yml, job `docs`).
import 'dart:io';

import 'package:ix_flutter/src/ix_colors/ix_theme_color_tokens.dart';

const _lightSource = 'lib/src/ix_colors/theme/ix_classic_light_colors.dart';
const _darkSource = 'lib/src/ix_colors/theme/ix_classic_dark_colors.dart';
const _output = '../../doc/tokens.md';

/// `#rrggbb` for an opaque color, `#aarrggbb` when it carries alpha, so a
/// semi-transparent token is never documented as if it were opaque.
String hex(int argb) {
  final rgb = (argb & 0xFFFFFF).toRadixString(16).padLeft(6, '0');
  final alpha = (argb >> 24) & 0xFF;
  if (alpha == 0xFF) return '#$rgb';
  return '#${alpha.toRadixString(16).padLeft(2, '0')}$rgb';
}

/// Reads `{ IxThemeColorToken.<token>: <argb> }` out of one generated
/// palette source: every `palette` entry names a `static const Color`
/// declared in the same file.
Map<String, int> readPalette(String path) {
  final source = File(path).readAsStringSync();
  final constants = <String, int>{};
  final constantPattern = RegExp(
    r'static const Color (\w+) = Color\(0x([0-9a-fA-F]{8})\);',
  );
  for (final match in constantPattern.allMatches(source)) {
    constants[match.group(1)!] = int.parse(match.group(2)!, radix: 16);
  }

  final palette = <String, int>{};
  final entryPattern = RegExp(r'IxThemeColorToken\.(\w+): (\w+),');
  for (final match in entryPattern.allMatches(source)) {
    final token = match.group(1)!;
    final constant = match.group(2)!;
    final value = constants[constant];
    if (value == null) {
      stderr.writeln('$path: $token maps to unknown constant `$constant`');
      exit(1);
    }
    palette[token] = value;
  }
  return palette;
}

void main() {
  if (!File(_lightSource).existsSync()) {
    stderr.writeln(
      'Cannot find $_lightSource -- run this from packages/ix_flutter:\n'
      '  cd packages/ix_flutter && dart run tool/gen_token_table.dart',
    );
    exit(1);
  }

  final light = readPalette(_lightSource);
  final dark = readPalette(_darkSource);

  final b = StringBuffer(
    '# Siemens iX color tokens (classic)\n'
    '\n'
    'Generated by `dart run tool/gen_token_table.dart` (from '
    '`packages/ix_flutter`) out of `IxClassicLightColors`/'
    '`IxClassicDarkColors`, the Dart mirrors of `@siemens/ix@5.2.1` '
    '`_variables.scss`. Do not edit by hand.\n'
    '\n'
    'Values are `#rrggbb`, or `#aarrggbb` where the token carries alpha. '
    'Read a token at runtime with `IxTheme.of(context).palette[token]`; see '
    '[theming.md](theming.md).\n'
    '\n'
    '| Token | Light | Dark |\n'
    '|---|---|---|\n',
  );
  for (final token in IxThemeColorToken.values) {
    final lightValue = light[token.name];
    final darkValue = dark[token.name];
    if (lightValue == null || darkValue == null) {
      stderr.writeln(
        '${token.name} is missing from '
        '${lightValue == null ? _lightSource : _darkSource}',
      );
      exit(1);
    }
    b.writeln('| `${token.name}` | ${hex(lightValue)} | ${hex(darkValue)} |');
  }

  File(_output).writeAsStringSync(b.toString());
  stdout.writeln(
    'doc/tokens.md written (${IxThemeColorToken.values.length} tokens)',
  );
}
